
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; File System: LittleFS
board_build.filesystem = littlefs

; Library Dependencies
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.8

; Build Flags
build_flags = 
    -D CORE_DEBUG_LEVEL=0             ; Reduce debug bloat
    -I firmware/SmartKey_Controller   ; Include header path

; Partition Scheme (Maximize App/SPIFFS split)
board_build.partitions = huge_app.csv
